name: Laravel/Lumen CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1.21'
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync All files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
#  post-deploy:
#    name: 🎉 Post-Deploy
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - name: Run migrations and seeders, clear cache for views, config and routes
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            cd public_html/
#            /opt/cpanel/ea-php80/root/usr/bin/php artisan migrate:fresh --seed --force
#            /opt/cpanel/ea-php80/root/usr/bin/php artisan config:clear
#            /opt/cpanel/ea-php80/root/usr/bin/php artisan view:clear
#            /opt/cpanel/ea-php80/root/usr/bin/php artisan route:cache
#          host: {...}
#          port: {...}
#          user: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.PRIVATE_KEY }}
